version: '3.8'
services:
  db:
    container_name: dev_db
    image: postgres:13
    volumes:
      - dev_db_orm:/var/lib/postgresql/data/
    env_file:
      - ./db.dev.env
    ports:
      - "5432:5432"
  pgadmin:
    container_name: dev_pgadmin
    image: dpage/pgadmin4
    volumes:
      - dev_pg_orm:/var/lib/pgadmin
    env_file:
      - ./pgadmin.dev.env
    ports:
      - "5050:80"

volumes:
  dev_db_orm:
  dev_pg_orm: